Add media query to the style.css file
Yidnekachew-cmd/Setup-and-mobile-version-skeleton pull request #4
Opened 2022-11-09 19:36 UTC by Yidnekachew-cmd

In this branch, I added a media query to the style.css file. I used a min-width 768px to make the portfolio responsive for the desktop.  In addition, this branch also has background images and thumbnails.

2022-11-09 20:23 UTC, topeogunleye requested changes
Hi @Yidnekachew-cmd, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 20:23 UTC, topeogunleye commented on index.html
> +                        <h2 class="title">Multi-Post Stories</h2>
- [ ] I kindly suggest that you add the grey circular icons present in the Figma design to your own design.

| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="877" alt="image" src="https://user-images.githubusercontent.com/52934128/200931509-7d892f49-fad4-4b13-aedf-b92d211c60b8.png">  | <img width="260" alt="image" src="https://user-images.githubusercontent.com/52934128/200932641-06362b7e-8a05-44f4-9c37-458417d3d5ba.png">  |

2022-11-09 20:23 UTC, topeogunleye commented on index.html
> +                <div class="desktop">
- [ ] I kindly suggest that you make sure that your website is properly responsive to look like the Figma design.
20% of your page requires an horizontal scroll bar to be viewed. Please see my video below for more explanation.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/52934128/200933552-a904864c-5dae-4068-9241-a9248a04cc9f.png">


https://www.loom.com/share/c56e74d7e441418f8102b08b9dd9e602

2022-11-10 07:07 UTC, Yidnekachew-cmd commented on index.html
> +                        <h2 class="title">Multi-Post Stories</h2>
I have inserted bullets as you suggested me. Thank you!

2022-11-10 07:08 UTC, topeogunleye commented on index.html
> +                        <h2 class="title">Multi-Post Stories</h2>
@Yidnekachew-cmd , That's great!

2022-11-10 07:08 UTC, Yidnekachew-cmd commented on index.html
> +                <div class="desktop">
I did the changes to my project. Thank you.

2022-11-10 07:09 UTC, topeogunleye commented on index.html
> +                <div class="desktop">
@Yidnekachew-cmd, you're welcome

2022-11-10 07:16 UTC, Olamarx approved these changes
Hi @Yidnekachew-cmd, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/ZhvduEq5hWKYsmhRAJ/giphy.gif"/>
## Highlights
- All linters passed ✔️ 
- Git and GitHub flow 👍🏼 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 07:46 UTC, merged